### PR TITLE
Fixed #7 and #8.

### LINKED ISSUE #7: wrong chest drop
## Description (Required)

The destroyed chest will not drop properly.
## Steps to reproduce the Issue (Required)

Place emerald chest
Destroy it (as player)
it drop a cs-corelib's head
image

## Expected behavior (Required)

The chest will drop normally
## Server Log / Error Report

Error: https://pastebin.com/VawhaPPk
Full log: https://pastebin.com/MUCK0rSL
## Environment (Required)

image

### PR DESCRIPTION
**Pull request by LinoxGH**
Used better indentation, fixed a couple issues, added some docs, updated sf version and refactored some code.

#7 and #8 are fixed.
#5 may also be fixed but needs testing.

### CODE REVIEW

**Comment by LinoxGH** [comment]
Btw please add Hacktoberfest labels to both repo and this pr.

**Review by TheBusyBiscuit — APPROVED** [review]
LGTM

**Comment by TheBusyBiscuit** [comment]
I added the "hacktoberfest" topic to this repository and this is gonna count now because of the review and merge anyway.

**Comment by LinoxGH** [comment]
Haha! Didn't even need a requested change. Like a pro 😎

**Comment by TheBusyBiscuit** [comment]
The only thing I would have suggested was to turn the second `if` into an `else if` but yeah that seemed too nitpicky to really request it as a change here.

**Comment by Volgeop** [comment]
Did someone test https://github.com/TheBusyBiscuit/PrivateStorage/issues/5 already?

**Comment by LinoxGH** [comment]
> Did someone test https://github.com/TheBusyBiscuit/PrivateStorage/issues/5 already?

No but you can be the first if you like.

**Comment by mrcoffee1026** [comment]
Tested, no effect on #5.  Safe does not break from explosive pickaxe, any items in the chest are dropped on the ground while still remaining inside the chest for as many times as you'd care to reuse your explosive pickaxe next to these chests.  Will be keeping these disabled for now.

**Comment by Volgeop** [comment]
OH :/

**Comment by mrcoffee1026** [comment]
Oh?  I don't know perhaps it is, I should probably copy the bug over in main slimefun then.

**Comment by TheBusyBiscuit** [comment]
> Oh? I don't know perhaps it is, I should probably copy the bug over in main slimefun then.

No.

**Comment by LinoxGH** [comment]
This is not an issue with the pickaxe. This is an issue with the wrong implementation of it in addons.

**Comment by Volgeop** [comment]
And can't this happens to normal plugins too? I think they won't think about interaction with Slimefun explosive pickaxe... so maybe some changes could be made there.

**Pull request merged**
